parameters:
  name: ""
  variablesFile: ""
  environmentName: ""
  azureSubscription: ""
  artifactDropName: drop
  uniquePrefix: adc

jobs:
  - deployment: Deploy
    displayName: ${{ parameters.name }}
    variables:
      - template: ${{ parameters.variablesFile }}
    pool:
      vmImage: ${{ variables.vmImage }}
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureResourceGroupDeployment@2
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                action: "Create Or Update Resource Group"
                resourceGroupName: ${{ variables.resourceGroupName }}
                location: ${{ variables.location }}
                templateLocation: "Linked artifact"
                csmFile: $(Pipeline.Workspace)/${{ parameters.artifactDropName }}/scm-resources-api-dotnetcore.json
                overrideParameters: -sku ${{ variables.appServicePlanSKU }} -webAppName ${{ parameters.uniquePrefix }}${{ variables.apiAppName }} -use32bitworker ${{ variables.use32bitworker }} -alwaysOn ${{ variables.alwaysOn }} -storageAccountName ${{ parameters.uniquePrefix }}${{ variables.storageAccountName }} -functionAppName ${{ parameters.uniquePrefix }}${{ variables.resizerFunctionName }} -applicationInsightsName ${{ variables.applicationInsightsName }} -serviceBusNamespaceName ${{ parameters.uniquePrefix }}${{ variables.serviceBusNamespaceName }}
            - task: AzureRmWebAppDeployment@4
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: apiApp
                webAppName: ${{ parameters.uniquePrefix }}${{ variables.apiAppName }}
                package: $(Pipeline.Workspace)/${{ parameters.artifactDropName }}/Adc.Scm.Resources.Api.zip
            - task: AzureRmWebAppDeployment@4
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: apiApp
                webAppName: ${{ parameters.uniquePrefix }}${{ variables.resizerFunctionName }}
                package: $(Pipeline.Workspace)/${{ parameters.artifactDropName }}/Adc.Scm.Resources.ImageResizer.zip
